version: '3.8'
services:
  api:
    build:
      context: ./app/app
      dockerfile: Dockerfile
    container_name: flask-api
    restart: unless-stopped
    ports:
    - "5001:5000"
    volumes:
    - ./app/app:/app
    links:
    - mysql-db
    depends_on:
    - mysql-db
    networks: 
      - flask_network

  mysql-db:
    image: mysql:5.7
    container_name: flask-db
    restart: unless-stopped
    environment:
      MYSQL_DB: ${MYSQL_DB_SERVER?Variable not set}
      MYSQL_USER: ${MYSQL_DB_API_USER?Variable not set}
      MYSQL_PASSWORD: ${MYSQL_DB_API_PASSWORD?Variable not set}
      MYSQL_DB_API: ${MYSQL_DB_API?Variable not set}
      MYSQL_DB_API_USER: ${MYSQL_DB_API_USER?Variable not set}
      MYSQL_DB_API_PASSWORD: ${MYSQL_DB_API?Variable not set}
      TZ: "Asia/Jakarta" # Add timezone
    ports:
      - ${MYSQL_DB_EXPOSE_PORT?Variable not set}:${MYSQL_DB_PORT?Variable not set}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./files:/files
    networks: 
      - flask_network

volumes:
  mysql_data:
    driver: local

networks: 
  flask_network:
    name: flask_network