version: '3.8'
services:
  api:
    build:
      context: ./app/app
      dockerfile: Dockerfile
    container_name: flask-api
    restart: always
    ports:
    - "5001:5000"
    volumes:
    - ./app/app:/app
    links:
    - db
    networks: 
      - flask_network

  db:
    image: mysql:5.7
    container_name: flask-db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks: 
      - flask_network

volumes:
  my-db:

networks: 
  flask_network:
    name: flask_network